### ISSUE TITLE
Task list 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#117]
- [ ] change the color of an unavailable button, it seems that it doesn’t work 
- [ ] if a user has an account, what for him the instruction in the 2nd step?
![3B1EAEE2-3819-4A2C-99CC-FF646D7100FF](https://user-images.githubusercontent.com/63041847/82201653-623ad680-9909-11ea-839b-6c513284e650.jpeg)
- [ ] swap sign in and log in, as out of habit a user can click on the right button 
![25B51867-A8B6-4CFB-B1F5-C71C062FB658](https://user-images.githubusercontent.com/63041847/82201860-a62ddb80-9909-11ea-8c90-998773389cf2.jpeg)
- [ ] change the title of the second step, users don’t understand it
@annamaksimik help 
![58BECAAF-89A2-4925-8F15-E48FFC09F684](https://user-images.githubusercontent.com/63041847/82202105-16d4f800-990a-11ea-828e-bf27d41c27a0.jpeg)
