### ISSUE TITLE
Instruction correction. Task list.

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#142]
- [ ] at the step "выдели слово или часть для перевода" the line "гулять пешком" dissapeared, when you click on the next step, after going to this slide, the word selection disappears
![image](https://user-images.githubusercontent.com/63041847/84482591-b20a8480-aca0-11ea-8db0-d17c9e0a5084.png)
![image](https://user-images.githubusercontent.com/63041847/84259220-d17aa380-ab20-11ea-8da2-23d63804945f.png)
![image](https://user-images.githubusercontent.com/63041847/84259889-cecc7e00-ab21-11ea-874b-c0277da88129.png)
- [ ] Selected this word in vertical subtitles
![image](https://user-images.githubusercontent.com/63041847/84482826-0dd50d80-aca1-11ea-8be8-5502230c9562.png)
- [ ] Change the design of hot keys, because all users thibk that they are clickable, @annamaksimik help with the design 
![image](https://user-images.githubusercontent.com/63041847/84482522-94d5b600-aca0-11ea-8ba6-85a8cee59847.png)

- [ ] in the instruction in the player change the language in the step with hot keys (Russian)
![image](https://user-images.githubusercontent.com/63041847/84256863-2c120080-ab1d-11ea-81a0-cdb150b57d92.png)
