### ISSUE TITLE
[1h]Player design corretion. Task list

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#169]
- [ ] Make the circle on the right near the cross
- [ ] in the extension dowloading window make the font bigger and fatter
![image](https://user-images.githubusercontent.com/63041847/84670352-b055f080-af2e-11ea-9cdb-85c6c1caccb3.png)
- [ ] Make the alignment with "Sign up", "Sign in", "Welcome"
![image](https://user-images.githubusercontent.com/63041847/84670792-370acd80-af2f-11ea-87bd-6515bf89ae92.png)
