### ISSUE TITLE
player correction. Task list:

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#195]
- [x] Align home screen in the player.
![image](https://user-images.githubusercontent.com/63041847/85379951-03d6c880-b545-11ea-83ca-18f22379f1ed.png)
- [x] You forgot to add " go to tutor" instead of " word repeat games"
![image](https://user-images.githubusercontent.com/63041847/85380087-2cf75900-b545-11ea-9ed0-1cca2164d541.png)
- [x] change the style of the buttons:
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=1291%3A1661
